version: '3.8'

services:
  cms-app:
    image: keerthanagande/cms-app:latest
    ports:
      - "9090:8080"   # map host 9090 to container 8080 (Tomcat default)
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: clinic_user
      MYSQL_PASSWORD: clinic_pass
      MYSQL_DATABASE: clinic_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
